<?php

use Drupal\Core\Url;
use Drupal\gallery\Navigation;


/**
 * gallery embed as paragraph in article
 * todo: add loading gallery thumbs here with "gallery_photo_preview"
 * @param $variables
 */
function gallery_preprocess_media(&$variables)
{
    if(
        isset($variables['content']['name']) &&
        'burda_gallery_in_paragraphs' == $variables['content']['name']['#view_mode'])
    {
        $gallery_id     = $variables['content']['name']['#object']->id();
        $relative_url   = \Drupal::service('path.alias_manager')->getAliasByPath('/media/' . $gallery_id);
        $absolute_url   = Url::fromUri('base:/' . $relative_url, array('absolute' => TRUE));

        $variables['gallery_url'] = $absolute_url->toString();
    }
}

/**
 * Get backlink from gallery to her article
 *
 * @param $variables
 * @return string - relative URL
 */
function gallery_preprocess_page(&$variables)
{
    /**
     *  We are on gallery page?
     */
    $media = \Drupal::routeMatch()->getParameter('media');
    if($media && 'gallery' == $media->bundle())
    {
        /**
         * add absolute link
         */
        $absolute_url = \Drupal::service('path.alias_manager')->getAliasByPath('/media/' . $media->id());
        $absolute_url = Url::fromUri('base:/' . $absolute_url, array('absolute' => TRUE));
        $variables['absolute_url'] = $absolute_url->toString();

        /**
         * Homepage, default backlink, fallback
         */
        $variables['preprocess_article_backlink'] = \Drupal::url('<front>');

        /**
         * backlink from gallery to the article
         */
        $query = \Drupal::request()->query;
        $from = $query->get('bnid');

        if($from)
        {
            $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $from]);
            if($url)
            {
                $variables['preprocess_article_backlink'] = $url->toString();
            }
        }
        else
        {
            /**
             * Find gallery used in paragraph
             */
            $paragraph = \Drupal::entityQuery('paragraph')
                ->condition('field_media', $media->id())
                ->execute();

            if($paragraph)
            {
                /**
                 * Find node where is paragraph used
                 */
                $find_node = \Drupal::entityQuery('node')
                    ->condition('field_paragraphs', array(end($paragraph)), 'IN')
                    ->execute();

                if($find_node)
                {
                    $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => end($find_node)]);
                    if($url)
                    {
                        $variables['preprocess_article_backlink'] = $url->toString();
                    }
                }
            }
        }
    }
}