<?php

use Drupal\Core\Url;
use Drupal\gallery\Navigation;

/**
 * @param $suggestions
 * @param $variables
 */
function gallery_theme_suggestions_html_alter(&$suggestions, &$variables)
{
    $media = \Drupal::routeMatch()->getParameter('media');
    if($media && 'gallery' == $media->bundle())
    {
        if(isset($_GET['tpl']) && 'ads' == $_GET['tpl'])
        {
            $suggestions[] = 'html__media__ads';
        };
    }
}

/**
 * @param $suggestions
 * @param $variables
 */
function gallery_theme_suggestions_page_alter(&$suggestions, &$variables)
{
    $media = \Drupal::routeMatch()->getParameter('media');
    if($media && 'gallery' == $media->bundle())
    {
        if(isset($_GET['tpl']) && 'ads' == $_GET['tpl'])
        {
            $suggestions[] = 'page__media__ads';
        };
    }
}

function gallery_preprocess_media(&$variables)
{
    //dpm($variables);
}

/**
 * Get backlink from gallery to her article
 *
 * @param $variables
 * @return string - relative URL
 */
function gallery_preprocess_page(&$variables)
{
    /**
     *  We are on gallery page?
     */
    $media = \Drupal::routeMatch()->getParameter('media');
    if($media && 'gallery' == $media->bundle())
    {
        /**
         * add absolute link
         */
        $absolute_url = \Drupal::service('path.alias_manager')->getAliasByPath('/media/' . $media->id());
        $absolute_url = Url::fromUri('base:/' . $absolute_url, array('absolute' => TRUE));
        $variables['absolute_url'] = $absolute_url->toString();
        $variables['#cache']['max-age'] = 0;

        /**
         * Homepage, default backlink, fallback
         */
        $variables['preprocess_article_backlink'] = \Drupal::url('<front>');

        /**
         * backlink from gallery to the article
         */
        $query = \Drupal::request()->query;
        $from = $query->get('bnid');

        if($from)
        {
            $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $from]);
            if($url)
            {
                $variables['preprocess_article_backlink'] = $url->toString();
            }
        }
        else
        {
            /**
             * Find gallery used in paragraph
             */
            $paragraph = \Drupal::entityQuery('paragraph')
                ->condition('field_media', $media->id())
                ->execute();

            if($paragraph)
            {
                /**
                 * Find node where is paragraph used
                 */
                $find_node = \Drupal::entityQuery('node')
                    ->condition('field_paragraphs', array(end($paragraph)), 'IN')
                    ->execute();

                if($find_node)
                {
                    $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => end($find_node)]);
                    if($url)
                    {
                        $variables['preprocess_article_backlink'] = $url->toString();
                    }
                }
            }
        }
    }
}


// todo: add loading gallery thumbs here with "gallery_photo_preview"


/**
 * Paragraphs - Gallery item
 * @param $variables
 */
function gallery_preprocess_paragraph(&$variables)
{
    $paragraph = $variables['paragraph'];
    $bundle = $paragraph->bundle();

    if ($bundle == 'gallery')
    {
        // todo
    }
}
